students/k3342/Bakhareva_Maria/lr2/HomeworkBoard/HomeworkBoard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assignments/', include('assignments.urls', namespace='assignments')),
]

students/k3342/Bakhareva_Maria/lr2/HomeworkBoard/assignments/urls.py
from django.urls import path
from .views import (
    register_student,
    login_student,
    task_list,
    create_task,
    submit_assignment,
    edit_assignment,
    admin_grades_list,
    show_only_my_grades,
    base_view,
    logout_student,
)

app_name = 'assignments'

urlpatterns = [
    # Учетная запись
    path('', base_view, name='base'),  # Главная страница
    path('register/', register_student, name='register'),
    path('login/', login_student, name='login'),
    path('logout/', logout_student, name='logout'),

    # Задания
    path('tasks/', task_list, name='task_list'),  # Список заданий
    path('tasks/create/', create_task, name='create_task'),  # Создание задания (только для админа)
    path('tasks/submit/<int:task_id>/', submit_assignment, name='submit_assignment'),  # Отправка задания
    path('tasks/edit/<int:assignment_id>/', edit_assignment, name='edit_assignment'),  # Редактирование задания

    # Оценки
    path('grades/', show_only_my_grades, name='my_grades'),  # Оценки текущего студента
    path('admin/grades/', admin_grades_list, name='admin_grades'),  # Оценки всех студентов (только админ)
]

students/k3342/Bakhareva_Maria/lr2/HomeworkBoard/templates/tasks/create_task.html
{% extends 'base.html' %}

{% block title %}Create Task{% endblock %}

{% block content %}
<h2>Create New Task</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create Task</button>
</form>
{% endblock %}

students/k3342/Bakhareva_Maria/lr2/HomeworkBoard/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block title %}Task List{% endblock %}

{% block content %}
<h2>Task List</h2>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Creation Date</th>
            <th>Due Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.date_issued }}</td>
                <td>{{ task.deadline }}</td>
                <td>
                    <a href="{% url 'assignments:submit_assignment' task.id %}" class="btn btn-success">Submit</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}